### ISSUE TITLE
Does not work with --prod flag (Angular 7)

### ISSUE THREAD

**Issue by MaksJS** [kamiazya/ngx-speech-recognition#149]
Got errors like : 

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'SpeechRecognitionModule' was called.

forRoot() should only "return", without any function call (actually const providers: Provider[] = SpeechRecognitionModule.buildProvidersFromConfig(config); and some array pushes).

I also got : 

ERROR in : Error: Internal error: unknown identifier undefined

**Comment by kamiazya** [comment]
@MaksJS 
Thank you for reporting!

I’ll check the repeatability.

**Comment by MaksJS** [comment]
@kamiazya you can reproduce it by running ng build --prod in the root of the projet

**Comment by kamiazya** [comment]
@MaksJS 
Thanks!
I could reproduce it in the way you said.

And I found a nice commit in your fork repository.
Please send me a pull request!

**Comment by MaksJS** [comment]
I've sent you a pull request. I've refactored all buildProvidersFromConfig logic into return statements of forRoot() and withConfig().

**Comment by kamiazya** [comment]
@MaksJS 

Thank you for sending PullRequest!

I merged and released this commit, I got the following another error.
```
ERROR in : Invalid provider for undefined. useClass cannot be undefined.
           Usually it happens when:
           1. There's a circular dependency (might be caused by using index.ts (barrel) files).
           2. Class was used before it was declared. Use forwardRef in this case.
```

I will continue to address this issue in this issue as well.

If you know the solution to this problem, please continue to support me.

**Comment by MaksJS** [comment]
@kamiazya I've debugged with console.log in node_modules@angular\compiler\bundles\compiler.umd.js

````javascript
        CompileMetadataResolver.prototype._validateProvider = function (provider) {
            console.log('type', provider);
            if (provider.hasOwnProperty('useClass') && provider.useClass == null) {
                this._reportError(syntaxError("Invalid provider for " + stringifyType(provider.provide) + ". useClass cannot be " + provider.useClass + ".\n           Usually it happens when:\n           1. There's a circular dependency (might be caused by using index.ts (barrel) files).\n           2. Class was used before it was declared. Use forwardRef in this case."));
            }
        };
````

```
type { useValue: true, provide: undefined }
type { useValue: false, provide: undefined }
type { useValue: 1, provide: undefined }
type { useClass: undefined, provide: undefined }
```

We got undefined for all the providers, it seems like there is a circular dependency. I think it's a problem with the way the classes are imported / exported in source files. There is no problem with your package "speech-synthesis" which I'm also using.

**Comment by kamiazya** [comment]
@MaksJS 
Now, I released a version that solved the problem of circular dependency!

I was greatly helped by detailed debugging and reports.
Thank you!

The build is now successful even with the `--prod` flag, as shown below.

```
$ ng add @kamiazya/ngx-speech-recognition
Skipping installation: Package already installed
    ✅️ Added dependency: @kamiazya/ngx-speech-recognition@0.4.3
    ✅️ Dependencies installed
    ✅️ SpeechRecognitionModule Imported to /src/app/app.module.ts
UPDATE package.json (1363 bytes)
UPDATE src/app/app.module.ts (446 bytes)
[###########################################################################################################################################] 1900/1900
$ ng build --prod
                                                                                 
Date: 2019-06-03T23:12:38.038Z
Hash: 2f457f8b83fd05caf766
Time: 16798ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.1e04665e16f944715fd2.js (es2015-polyfills) 56.4 kB [initial] [rendered]
chunk {2} main.59dad101e63add5094a3.js (main) 162 kB [initial] [rendered]
chunk {3} polyfills.8bbb231b43165d65d357.js (polyfills) 41 kB [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]
```

**Comment by MaksJS** [comment]
@kamiazya It works great now, thanks!
