### ISSUE TITLE
Error on click start button many

### ISSUE THREAD

**Issue by devamir** [kamiazya/ngx-speech-recognition#2]
Hi,
I tried installing this app and on clicking "Start it doesn't captures the voice.
Also i get error in console even after clicking end button.
![ngx-speech-recognition-error](https://user-images.githubusercontent.com/3250628/42504872-ad7b0298-845a-11e8-8945-280a9d409208.PNG)

**Comment by kamiazya** [comment]
@devamir 

I pressed the button during speech recognition because I got an error when I pressed the `start` button during speech recognition.

Also I thought that it was better to have this as an API, I published it as Observale with` started$ `of` RxSpeechRecognitionService`.

Thanks!
