### ISSUE TITLE
Cannot find name 'SpeechGrammarList'.

### ISSUE THREAD

**Issue by tilakdewangan-gep** [kamiazya/ngx-speech-recognition#266]
Hi Team,

I am trying to implement a voice search using this library by following [npmjs](https://www.npmjs.com/package/@kamiazya/ngx-speech-recognition) link on my angular 5 projects but  I am getting a few errors on that (see below) though I am able to compile this i.e compiled successfully with errors.- 

`
ERROR in node_modules/@kamiazya/ngx-speech-recognition/lib/adapter.d.ts(1,45): error TS2304: Cannot find name 'SpeechGrammarList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/adapter.d.ts(2,61): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/rx-speech-recognition.service.d.ts(1,22): error TS2305: Module '"C:/Users/Desktop/CodeHub/Demo/ngx-speech-recognition-demo/node_modules/rxjs/Rx"' has no exported member 'UnaryFunction'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/rx-speech-recognition.service.d.ts(5,59): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/rx-speech-recognition.service.d.ts(5,95): error TS2304: Cannot find name 'SpeechRecognitionResultList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.common.d.ts(9,25): error TS2304: Cannot find name 'SpeechRecognition'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,426): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,479): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,530): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(26,20): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(27,21): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.common.d.ts(9,25): error TS2304: Cannot find name 'SpeechRecognition'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,426): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,479): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,530): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(26,20): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(27,21): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(28,19): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(2,64): error TS2304: Cannot find name 'SpeechGrammarList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(14,74): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(15,75): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(16,73): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(2,16): error TS2304: Cannot find name 'SpeechGrammarList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(14,21): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(15,22): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(16,20): error TS2304: Cannot find name 'SpeechRecognitionError'.
src/app/app.component.ts(29,25): error TS2304: Cannot find name 'SpeechRecognitionResultList'.
`

Could you please help me to solve this?

**Comment by kamiazya** [comment]
@tilakdewangan-gep 

Thank you for using it!
The latest version is not compatible with Angular 5 series, so try using the `0.1.1` version.

Alternatively, you can use the latest version by adding the `@types/webspeechapi` package to devDependencies.
https://www.npmjs.com/package/@types/webspeechapi

**Comment by poojas17** [comment]
Hi Team,

I am trying to use this library in my angular 6 projects but I am getting below errors: 
ERROR in node_modules/@kamiazya/ngx-speech-recognition/lib/adapter.d.ts(1,45): error TS2304: Cannot find name 'SpeechGrammarList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/adapter.d.ts(2,61): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/rx-speech-recognition.service.d.ts(5,59): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/rx-speech-recognition.service.d.ts(5,95): error TS2304: Cannot find name 'SpeechRecognitionResultList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.common.d.ts(9,25): error TS2304: Cannot find name 'SpeechRecognition'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,426): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,479): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(19,530): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(26,20): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(27,21): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.service.d.ts(28,19): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(2,64): error TS2304: Cannot find name 'SpeechGrammarList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(14,74): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(15,75): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/service/speech-recognition.token.d.ts(16,73): error TS2304: Cannot find name 'SpeechRecognitionError'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(2,16): error TS2304: Cannot find name 'SpeechGrammarList'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(14,21): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(15,22): error TS2304: Cannot find name 'SpeechRecognitionEvent'.
node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition.config.d.ts(16,20): error TS2304: Cannot find name 'SpeechRecognitionError'.


I have tried the above-mentioned solution: 
a. Tried changing version to 0.1.1 
b. Added  "@types/webspeechapi": "0.0.29" in dev dependency as well

Could you please help me resolve this issue?
