### ISSUE TITLE
angular 6

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [kamiazya/ngx-speech-recognition#4]
Cool project, I'd like to use it in a demo. Is there already an initiative to move to Angular 6?

**Comment by kamiazya** [comment]
@tobi-or-not-tobi 

I made it work on Angular 6!

**Comment by kamiazya** [comment]
@tobi-or-not-tobi 

I found your fork.

I don't understand well around `public_api.ts`, so I will help you if I have a Pull Request.
