### ISSUE TITLE
webspeechapi type isn't defined

### ISSUE THREAD

**Issue by Tristam2** [kamiazya/ngx-speech-recognition#405]
Hey, I'm running Angular 8.

When starting the dev server with the SpeechRecognitionService, I get these errors :

`ERROR in node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/adapter/adapter.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeechapi'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/adapter/adapter.d.ts(2,39): error TS2304: Cannot find name 'SpeechRecognitionStatic'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/adapter/adapter.d.ts(4,39): error TS2304: Cannot find name 'SpeechGrammarListStatic'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/adapter/event.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeechapi'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/service/rx-speech-recognition.service.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeec
hapi'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/service/speech-recognition.common.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeechapi
'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/service/speech-recognition.service.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeechap
i'.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/service/speech-recognition.token.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeechapi'
.
    node_modules/@kamiazya/ngx-speech-recognition/lib/speech-recognition/speech-recognition.config.d.ts(1,23): error TS2688: Cannot find type definition file for 'webspeechapi'.
`

**Comment by kamiazya** [comment]
This library can only support Angular 7 and below.
Try it with Angular 7 as your project.

Thanks.

**Comment by kamiazya** [comment]
NOTE

There is work that supports Angular 8, but the release date is undecided.

https://github.com/kamiazya/ngx-speech-recognition/pull/334

If you can help, Pull Request is welcome.

Thanks.
