### ISSUE TITLE
Build Failed with Angular 6

### ISSUE THREAD

**Issue by poojas17** [kamiazya/ngx-speech-recognition#464]
Hi Team,

I'm using this library with my Angular 6 project with the following versions:
ngx-speech-recognition: "0.2.2"
@types/webspeechapi: "0.0.29"

It appears to be linked with  #149 
![image](https://user-images.githubusercontent.com/21245753/73597709-dddc6780-4554-11ea-8135-b66fac0040d4.png)

I'm able to compile my project but not build it. 
The error shown in app.module.ts is :
node_modules/@kamiazya/ngx-speech-recognition/kamiazya-ngx-speech-recognition"' has no exported member 'SpeechRecognitionService'.

Can you please help me fix this issue?

**Comment by kamiazya** [comment]
@poojas17 

Sorry, Angular 6 support is not going to be done from now.

Since this project is MIT, I recommend you to copy it in your project, modify it, and use it :)

Thanks.
