### ISSUE TITLE
Speech Recognition is not defined on Firefox

### ISSUE THREAD

**Issue by aborderon** [kamiazya/ngx-speech-recognition#546]
Hello,

I'm reporting a problem, I integrated ngx-speech-recognition in my Angular application.

I use the following configuration:

- Angular: 8
- Typescript: 3.4.5
- ngx-speech-recognition: 0.4.3

Everything works fine on Chrome no problem, I know that speech recognition does not work on Firefox but I have an error message which breaks the application:

![image](https://user-images.githubusercontent.com/6728728/78470809-667dac80-772c-11ea-8ac4-e599af3dfce1.png)

Do you have a solution to offer me?

Thank you.

**Comment by kamiazya** [comment]
@aborderon 

Hi,

Thanks for using my library!



As a premise, this library is designed to be dependent on the browser implementation.

So there is no plan for this library to do anything to support FireFox.

However, if you look at [the browser support status](https://caniuse.com/#feat=speech-recognition), the following annotations are attached to FireFox's voice recognition API.

> Firefox currently has a `media.webspeech.recognition.enable` flag in about:config for this, but actual support is waiting for permissions to be sorted out.

There is also [a blog](https://hacks.mozilla.org/2016/01/firefox-and-the-web-speech-api/), so it might be better to try it while referring to this.

Thank you.

**Comment by aborderon** [comment]
Hello, thank you for your return.

Yes I know that it is not supported on firefox.

I do not wish to use it on firefox I just wish that it does not break the application because it works well on chrome.

Is there no way to ignore it on Firefox?

**Comment by kamiazya** [comment]
@aborderon 

How about using polyfill?

Like a ...

- https://github.com/anteloe/speech-polyfill

However, since the code needs to be called without the first argument as shown below, the interface needs to be changed.

https://github.com/kamiazya/ngx-speech-recognition/blob/master/projects/ngx-speech-recognition/src/lib/service/speech-recognition.common.ts#L7

I'm sorry, but I can't suggest any other way.

Thanks.

**Comment by ghachemsaif** [comment]
@aborderon
You can make a parent component with : 
```
declare var SpeechRecognition; // in top with the imports
  CheckIfSupproted(){
      if(SpeechRecognition){
        return true
      }
      return false
    }
```
