### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by ahmad-elbatanouni** [kamiazya/ngx-speech-recognition#63]
It would be really nice if you added a function to add some configuration .. at least to change the language.

**Comment by kamiazya** [comment]
Thanks @ahmad-elbatanouni 

It is designed to control behaviors by adding settings to Providers.

Or, You can set it when importing with AppModule etc. by using `SpeechRecognitionModule.withConfig` API.

* [Provider Pattern Example](https://github.com/kamiazya/ngx-speech-recognition/blob/master/src/demo/sub/components/sub/sub.component.ts)
* [Module Pattern Example](https://github.com/kamiazya/ngx-speech-recognition/blob/master/src/demo/demo.module.ts)

Can you solve your request with this?

**Comment by kamiazya** [comment]
I added example to README.
